### PR TITLE
[Closes #236] Operator space false positive

### LINKED ISSUE #236: Possible false positive?
Hi,

I'm trying to resolve an issue I'm encountering with Elvis on this piece of code within a EUnit test.

```erlang
ip_results_to_json_test() ->
    ?assertEqual(ip_results_to_json([{{127, 0, 0, 253}, not_vulnerable}, {{127, 0, 0, 252}, not_vulnerable}]),
            <<"[{\"address\":\"127.0.0.253\",\"stat\":\"not_vulnerable\"},{\"address\":\"127.0.0.252\",\"stat\":\"not_vulnerable\"}]">>).
```

The last of those lines is line 39 of the code, producing this error:

```shell
# src/ipmangle.erl [FAIL]
  - operator_spaces
    - Missing space after "," on line 39
```

As far as I can see, that is binary data, and it shouldn't be considering those commas to be operators. Implementing those spaces changes the data the function is expecting.

If it helps, the complete codebase is here: https://github.com/technion/erlvulnscan

It's my first Erlang project so I could easily be missing something obvious :)

### PR DESCRIPTION
**Pull request by jfacorro**
#236

### CODE REVIEW

File: test/examples/fail_operator_spaces.erl [hunk 1]
```diff
@@ -23,4 +23,24 @@ function4(Should, <<_:10/binary, ",", _/binary>>) ->
 
 function5() ->
     User = #{name => <<"Juan">>, email => <<"juan@inaka.com">>},
-    <<"juan@inaka.com">> = maps:get(email,User).
\ No newline at end of file
```
Comment (gadgetci) [inline test/examples/fail_operator_spaces.erl]: According to **Elvis**:
> Missing space after "," on line 26

**Comment by gadgetci** [comment]
According to **Elvis**:
> Dependency 'katana' is not using appropriate protocol, please change this to something like 'https://.*'

File: test/examples/fail_operator_spaces.erl [hunk 2]
```diff
@@ -1,6 +1,6 @@
 -module(fail_operator_spaces).
 
--export([function1/2,function2/2, function3/2, function4/2, function5/0]).
+-export([function1/2,function2/2, function3/2, function4/2, function5/0, tag_filters/2]).
```
Comment (gadgetci) [inline test/examples/fail_operator_spaces.erl]: According to **Elvis**:
> Line 3 is too long: -export([function1/2,function2/2, function3/2, function4/2, function5/0, tag_filters/2])..

Comment (gadgetci) [inline test/examples/fail_operator_spaces.erl]: According to **Elvis**:
> Missing space after "," on line 3

File: test/examples/fail_operator_spaces.erl [hunk 3]
```diff
@@ -23,4 +23,24 @@ function4(Should, <<_:10/binary, ",", _/binary>>) ->
...
\ No newline at end of file
+  <<"juan@inaka.com">> = maps:get(email,User).
+
+tag_filters(DocName, #{conn := Conn} = State) ->
+  TableName = atom_to_list(DocName),
+  Sql = ["SELECT "
+         " 'tag' AS \"type\", "
+         " tag_name AS value, "
+         " COUNT(1) AS \"count\" "
+         "FROM ( "
```
Comment (gadgetci) [inline test/examples/fail_operator_spaces.erl]: According to **Elvis**:
> Missing space after "," on line 35

Comment (gadgetci) [inline test/examples/fail_operator_spaces.erl]: According to **Elvis**:
> Missing space after "," on line 35

File: test/examples/fail_operator_spaces.erl (hunk 2 above)
Comment (gadgetci) [inline test/examples/fail_operator_spaces.erl]: According to **Elvis**:
> Missing space after "," on line 3

Comment (gadgetci) [inline test/examples/fail_operator_spaces.erl]: According to **Elvis**:
> Line 3 is too long: -export([function1/2,function2/2, function3/2, function4/2, function5/0, tag_filters/2])..

File: test/examples/fail_operator_spaces.erl (hunk 1 above)
Comment (gadgetci) [inline test/examples/fail_operator_spaces.erl]: According to **Elvis**:
> Missing space after "," on line 26

File: test/examples/fail_operator_spaces.erl (hunk 3 above)
Comment (gadgetci) [inline test/examples/fail_operator_spaces.erl]: According to **Elvis**:
> Missing space after "," on line 35

File: test/examples/fail_operator_spaces.erl (hunk 2 above)
Comment (gadgetci) [inline test/examples/fail_operator_spaces.erl]: According to **Elvis**:
> Missing space after "," on line 3

Comment (gadgetci) [inline test/examples/fail_operator_spaces.erl]: According to **Elvis**:
> Line 3 is too long: -export([function1/2,function2/2, function3/2, function4/2, function5/0, tag_filters/2])..

File: test/examples/fail_operator_spaces.erl (hunk 3 above)
Comment (gadgetci) [inline test/examples/fail_operator_spaces.erl]: According to **Elvis**:
> Missing space after "," on line 35

File: test/examples/fail_operator_spaces.erl (hunk 1 above)
Comment (gadgetci) [inline test/examples/fail_operator_spaces.erl]: According to **Elvis**:
> Missing space after "," on line 26

File: test/examples/fail_operator_spaces.erl (hunk 2 above)
Comment (gadgetci) [inline test/examples/fail_operator_spaces.erl]: According to **Elvis**:
> Missing space after "," on line 3

File: src/elvis_style.erl [hunk 4]
```diff
@@ -609,12 +609,17 @@ check_operator_spaces_rule(Line, Num, {Position, Operator}, Root) ->
...
+                            not_found -> undefined;
+                            {ok, Token} -> ktn_code:type(Token)
+                        end,
+            case {Type, TokenType} of
+                {atom, _}           -> [];
+                {binary_element, _} -> [];
+                {string, _}         -> [];
+                {char, _}           -> [];
+                {comment, _}        -> [];
+                {_, string}         -> [];
```
Comment (HernanRivasAcosta) [inline src/elvis_style.erl]: Why matching all this cases? If I'm not mistaken it would either be ``undefined`` or any of your valid options. Wouldn't matching undefined and have an otherwise default behaviour save lines?

File: test/examples/fail_operator_spaces.erl [hunk 5]
```diff
@@ -23,4 +23,24 @@ function4(Should, <<_:10/binary, ",", _/binary>>) ->
 
 function5() ->
     User = #{name => <<"Juan">>, email => <<"juan@inaka.com">>},
-    <<"juan@inaka.com">> = maps:get(email,User).
\ No newline at end of file
+  <<"juan@inaka.com">> = maps:get(email,User).
```
Comment (HernanRivasAcosta) [inline test/examples/fail_operator_spaces.erl]: Are you using 2 or 4 spaces? Line 25 is using 4.

File: test/xref_SUITE.erl [hunk 6]
```diff
@@ -0,0 +1,26 @@
...
+-export(
+   [
+    all/0,
+    xref/1
+   ]
+  ).
+
+-spec all() -> [atom()].
+all() ->
+  ExcludedFuns = [all, module_info],
```
Comment (HernanRivasAcosta) [inline test/xref_SUITE.erl]: Why exclude ``all`` if it has arity 0?

File: src/elvis_code.erl [hunk 7]
```diff
@@ -128,6 +129,16 @@ is_at_location(Node = #{attrs := #{location := {Line, NodeCol}}},
 is_at_location(_, _) ->
     false.
 
+-spec find_token(ktn_code:tree_node(), {integer(), integer()}) ->
+    undefined | {ok, map()}.
```
Comment (HernanRivasAcosta) [inline src/elvis_code.erl]: This spec says it returns undefined, but it returns ``not_found`` and it's converted to undefined elvis_style.erl@609

File: src/elvis_code.erl [hunk 8]
```diff
@@ -128,6 +129,16 @@ is_at_location(Node = #{attrs := #{location := {Line, NodeCol}}},
...
+find_token(Root, Location) ->
+    Fun = fun (Token) -> is_at_location(Token, Location) end,
+    Tokens = ktn_code:attr(tokens, Root),
+    case lists:filter(Fun, Tokens) of
+        [] -> not_found;
+        [Token | _] -> {ok, Token}
```
Comment (HernanRivasAcosta) [inline src/elvis_code.erl]: Also, is this a token or a map?

File: src/elvis_style.erl (hunk 4 above)
Comment (jfacorro) [inline src/elvis_style.erl]: We have to check for those types of nodes or tokens where an operator without a space is acceptable. An alternative would be to match for all that shouldn't have it, but in either case there needs to be an explicit specification of the valid (or invalid) types of nodes/tokens.

File: test/examples/fail_operator_spaces.erl (hunk 2 above)
Comment (gadgetci) [inline test/examples/fail_operator_spaces.erl]: According to **Elvis**:
> Missing space after "," on line 3

File: test/examples/fail_operator_spaces.erl (hunk 1 above)
Comment (gadgetci) [inline test/examples/fail_operator_spaces.erl]: According to **Elvis**:
> Missing space after "," on line 26

File: test/examples/fail_operator_spaces.erl [hunk 9]
```diff
@@ -23,4 +23,24 @@ function4(Should, <<_:10/binary, ",", _/binary>>) ->
...
\ No newline at end of file
+    <<"juan@inaka.com">> = maps:get(email,User).
+
+tag_filters(DocName, #{conn := Conn} = State) ->
+  TableName = atom_to_list(DocName),
+  Sql = ["SELECT "
+         " 'tag' AS \"type\", "
+         " tag_name AS value, "
+         " COUNT(1) AS \"count\" "
+         "FROM ( "
```
Comment (gadgetci) [inline test/examples/fail_operator_spaces.erl]: According to **Elvis**:
> Missing space after "," on line 35

File: test/examples/fail_operator_spaces.erl (hunk 2 above)
Comment (gadgetci) [inline test/examples/fail_operator_spaces.erl]: According to **Elvis**:
> Line 3 is too long: -export([function1/2,function2/2, function3/2, function4/2, function5/0, tag_filters/2])..

File: test/xref_SUITE.erl (hunk 6 above)
Comment (jfacorro) [inline test/xref_SUITE.erl]: It's a comprehensive exclusion list.

File: test/examples/fail_operator_spaces.erl (hunk 9 above)
Comment (gadgetci) [inline test/examples/fail_operator_spaces.erl]: According to **Elvis**:
> Missing space after "," on line 35

File: test/examples/fail_operator_spaces.erl (hunk 2 above)
Comment (gadgetci) [inline test/examples/fail_operator_spaces.erl]: According to **Elvis**:
> Line 3 is too long: -export([function1/2,function2/2, function3/2, function4/2, function5/0, tag_filters/2])..

Comment (gadgetci) [inline test/examples/fail_operator_spaces.erl]: According to **Elvis**:
> Missing space after "," on line 3

File: test/examples/fail_operator_spaces.erl (hunk 1 above)
Comment (gadgetci) [inline test/examples/fail_operator_spaces.erl]: According to **Elvis**:
> Missing space after "," on line 26

File: test/examples/fail_operator_spaces.erl (hunk 2 above)
Comment (gadgetci) [inline test/examples/fail_operator_spaces.erl]: According to **Elvis**:
> Missing space after "," on line 3

File: test/examples/fail_operator_spaces.erl (hunk 1 above)
Comment (gadgetci) [inline test/examples/fail_operator_spaces.erl]: According to **Elvis**:
> Missing space after "," on line 26
