### PR TITLE
[Closes #239] Updated katana dep to 0.2.7, add spec with fun((...) -> ok)

### LINKED ISSUE #239: Unhandled abstract form issue with fun((...)
this spec:
```-spec module_map(state(), abstract_function()) -> fun((...) -> ok | {error,term()}).```

causes these errors:
```
Error: '{unhandled_abstract_form,
                           {type,[{line,114},{column,55},
                                   {text,"("}],any}}' while applying rule 'no_spec_with_records'.
 Error: '{unhandled_abstract_form,
                           {type,[{line,114},{column,55},
                                  {text,"("}],any}}' while applying rule 'state_record_and_type'.
```

it is a valid syntax for specs `fun((...) -> ` means a fun of any arity returning a specific type.
```
Fun :: fun()                  %% any function
       | fun((...) -> Type)     %% any arity, returning Type
       | fun(() -> Type)
       | fun((TList) -> Type)
```

### PR DESCRIPTION
**Pull request by jfacorro**
#239

### CODE REVIEW

File: test/examples/fail_dont_repeat_yourself.erl [hunk 1]
```diff
@@ -10,13 +10,16 @@ repeated_complexity_5(X, Y) ->
...
+            Y -> io:format("Y");
+            _ -> <<"ok">>
+        end,
 
-    case Y of
-        X -> io:format("Y");
-        _ -> <<"ok">>
-    end.
+    W = case Z of
+            X -> io:format("Y");
```
Comment (HernanRivasAcosta) [inline test/examples/fail_dont_repeat_yourself.erl]: X and Z can never be equal unless X is ``ok`` or ``<<"ok">>``, is this intended?

Comment (jfacorro) [inline test/examples/fail_dont_repeat_yourself.erl]: This file is just for testing purposes, so that duplicated structures are detected by the `dont_repeat_yourself` rule. The code doesn't necessarily have to be functional.
